apiVersion: v1
kind: Secret
metadata:
  name: kafka-jaas
type: Opaque
stringData:
  jaas.conf: |-
    Client {
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="kafka"
          password="passcode";
    };

